agents:
  queue: hosted

cache: ".buildkite/cache-volume"

env:
  MISE_GITHUB_ATTESTATIONS: "false"
  MISE_RUBY_GITHUB_ATTESTATIONS: "false"

common_mise_plugin: &mise_plugin
  version: 2026.6.6

steps:
  - group: "test"
    steps:
      - label: "test build"
        command: echo "hello world 🐣" 